// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Admin                 *admin
	Class                 *class
	H1Attendance          *h1Attendance
	H1Class               *h1Class
	H1ClassCourse         *h1ClassCourse
	H1Course              *h1Course
	H1Enrollment          *h1Enrollment
	H1Schedule            *h1Schedule
	H1Semester            *h1Semester
	H1Student             *h1Student
	H1StudentSemesterBill *h1StudentSemesterBill
	Info                  *info
	Major                 *major
	Msg                   *msg
	School                *school
	User                  *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	Class = &Q.Class
	H1Attendance = &Q.H1Attendance
	H1Class = &Q.H1Class
	H1ClassCourse = &Q.H1ClassCourse
	H1Course = &Q.H1Course
	H1Enrollment = &Q.H1Enrollment
	H1Schedule = &Q.H1Schedule
	H1Semester = &Q.H1Semester
	H1Student = &Q.H1Student
	H1StudentSemesterBill = &Q.H1StudentSemesterBill
	Info = &Q.Info
	Major = &Q.Major
	Msg = &Q.Msg
	School = &Q.School
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Admin:                 newAdmin(db, opts...),
		Class:                 newClass(db, opts...),
		H1Attendance:          newH1Attendance(db, opts...),
		H1Class:               newH1Class(db, opts...),
		H1ClassCourse:         newH1ClassCourse(db, opts...),
		H1Course:              newH1Course(db, opts...),
		H1Enrollment:          newH1Enrollment(db, opts...),
		H1Schedule:            newH1Schedule(db, opts...),
		H1Semester:            newH1Semester(db, opts...),
		H1Student:             newH1Student(db, opts...),
		H1StudentSemesterBill: newH1StudentSemesterBill(db, opts...),
		Info:                  newInfo(db, opts...),
		Major:                 newMajor(db, opts...),
		Msg:                   newMsg(db, opts...),
		School:                newSchool(db, opts...),
		User:                  newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin                 admin
	Class                 class
	H1Attendance          h1Attendance
	H1Class               h1Class
	H1ClassCourse         h1ClassCourse
	H1Course              h1Course
	H1Enrollment          h1Enrollment
	H1Schedule            h1Schedule
	H1Semester            h1Semester
	H1Student             h1Student
	H1StudentSemesterBill h1StudentSemesterBill
	Info                  info
	Major                 major
	Msg                   msg
	School                school
	User                  user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Admin:                 q.Admin.clone(db),
		Class:                 q.Class.clone(db),
		H1Attendance:          q.H1Attendance.clone(db),
		H1Class:               q.H1Class.clone(db),
		H1ClassCourse:         q.H1ClassCourse.clone(db),
		H1Course:              q.H1Course.clone(db),
		H1Enrollment:          q.H1Enrollment.clone(db),
		H1Schedule:            q.H1Schedule.clone(db),
		H1Semester:            q.H1Semester.clone(db),
		H1Student:             q.H1Student.clone(db),
		H1StudentSemesterBill: q.H1StudentSemesterBill.clone(db),
		Info:                  q.Info.clone(db),
		Major:                 q.Major.clone(db),
		Msg:                   q.Msg.clone(db),
		School:                q.School.clone(db),
		User:                  q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Admin:                 q.Admin.replaceDB(db),
		Class:                 q.Class.replaceDB(db),
		H1Attendance:          q.H1Attendance.replaceDB(db),
		H1Class:               q.H1Class.replaceDB(db),
		H1ClassCourse:         q.H1ClassCourse.replaceDB(db),
		H1Course:              q.H1Course.replaceDB(db),
		H1Enrollment:          q.H1Enrollment.replaceDB(db),
		H1Schedule:            q.H1Schedule.replaceDB(db),
		H1Semester:            q.H1Semester.replaceDB(db),
		H1Student:             q.H1Student.replaceDB(db),
		H1StudentSemesterBill: q.H1StudentSemesterBill.replaceDB(db),
		Info:                  q.Info.replaceDB(db),
		Major:                 q.Major.replaceDB(db),
		Msg:                   q.Msg.replaceDB(db),
		School:                q.School.replaceDB(db),
		User:                  q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Admin                 IAdminDo
	Class                 IClassDo
	H1Attendance          IH1AttendanceDo
	H1Class               IH1ClassDo
	H1ClassCourse         IH1ClassCourseDo
	H1Course              IH1CourseDo
	H1Enrollment          IH1EnrollmentDo
	H1Schedule            IH1ScheduleDo
	H1Semester            IH1SemesterDo
	H1Student             IH1StudentDo
	H1StudentSemesterBill IH1StudentSemesterBillDo
	Info                  IInfoDo
	Major                 IMajorDo
	Msg                   IMsgDo
	School                ISchoolDo
	User                  IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:                 q.Admin.WithContext(ctx),
		Class:                 q.Class.WithContext(ctx),
		H1Attendance:          q.H1Attendance.WithContext(ctx),
		H1Class:               q.H1Class.WithContext(ctx),
		H1ClassCourse:         q.H1ClassCourse.WithContext(ctx),
		H1Course:              q.H1Course.WithContext(ctx),
		H1Enrollment:          q.H1Enrollment.WithContext(ctx),
		H1Schedule:            q.H1Schedule.WithContext(ctx),
		H1Semester:            q.H1Semester.WithContext(ctx),
		H1Student:             q.H1Student.WithContext(ctx),
		H1StudentSemesterBill: q.H1StudentSemesterBill.WithContext(ctx),
		Info:                  q.Info.WithContext(ctx),
		Major:                 q.Major.WithContext(ctx),
		Msg:                   q.Msg.WithContext(ctx),
		School:                q.School.WithContext(ctx),
		User:                  q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
