// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"demo/dal/model"
)

func newH1Attendance(db *gorm.DB, opts ...gen.DOOption) h1Attendance {
	_h1Attendance := h1Attendance{}

	_h1Attendance.h1AttendanceDo.UseDB(db, opts...)
	_h1Attendance.h1AttendanceDo.UseModel(&model.H1Attendance{})

	tableName := _h1Attendance.h1AttendanceDo.TableName()
	_h1Attendance.ALL = field.NewAsterisk(tableName)
	_h1Attendance.ID = field.NewInt64(tableName, "id")
	_h1Attendance.ScheduleID = field.NewInt64(tableName, "schedule_id")
	_h1Attendance.StudentID = field.NewInt64(tableName, "student_id")
	_h1Attendance.CheckedAt = field.NewTime(tableName, "checked_at")
	_h1Attendance.Status = field.NewString(tableName, "status")
	_h1Attendance.MakeupScheduleID = field.NewInt64(tableName, "makeup_schedule_id")

	_h1Attendance.fillFieldMap()

	return _h1Attendance
}

type h1Attendance struct {
	h1AttendanceDo h1AttendanceDo

	ALL              field.Asterisk
	ID               field.Int64
	ScheduleID       field.Int64
	StudentID        field.Int64
	CheckedAt        field.Time
	Status           field.String
	MakeupScheduleID field.Int64

	fieldMap map[string]field.Expr
}

func (h h1Attendance) Table(newTableName string) *h1Attendance {
	h.h1AttendanceDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Attendance) As(alias string) *h1Attendance {
	h.h1AttendanceDo.DO = *(h.h1AttendanceDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Attendance) updateTableName(table string) *h1Attendance {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.ScheduleID = field.NewInt64(table, "schedule_id")
	h.StudentID = field.NewInt64(table, "student_id")
	h.CheckedAt = field.NewTime(table, "checked_at")
	h.Status = field.NewString(table, "status")
	h.MakeupScheduleID = field.NewInt64(table, "makeup_schedule_id")

	h.fillFieldMap()

	return h
}

func (h *h1Attendance) WithContext(ctx context.Context) IH1AttendanceDo {
	return h.h1AttendanceDo.WithContext(ctx)
}

func (h h1Attendance) TableName() string { return h.h1AttendanceDo.TableName() }

func (h h1Attendance) Alias() string { return h.h1AttendanceDo.Alias() }

func (h h1Attendance) Columns(cols ...field.Expr) gen.Columns {
	return h.h1AttendanceDo.Columns(cols...)
}

func (h *h1Attendance) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Attendance) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 6)
	h.fieldMap["id"] = h.ID
	h.fieldMap["schedule_id"] = h.ScheduleID
	h.fieldMap["student_id"] = h.StudentID
	h.fieldMap["checked_at"] = h.CheckedAt
	h.fieldMap["status"] = h.Status
	h.fieldMap["makeup_schedule_id"] = h.MakeupScheduleID
}

func (h h1Attendance) clone(db *gorm.DB) h1Attendance {
	h.h1AttendanceDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Attendance) replaceDB(db *gorm.DB) h1Attendance {
	h.h1AttendanceDo.ReplaceDB(db)
	return h
}

type h1AttendanceDo struct{ gen.DO }

type IH1AttendanceDo interface {
	gen.SubQuery
	Debug() IH1AttendanceDo
	WithContext(ctx context.Context) IH1AttendanceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1AttendanceDo
	WriteDB() IH1AttendanceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1AttendanceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1AttendanceDo
	Not(conds ...gen.Condition) IH1AttendanceDo
	Or(conds ...gen.Condition) IH1AttendanceDo
	Select(conds ...field.Expr) IH1AttendanceDo
	Where(conds ...gen.Condition) IH1AttendanceDo
	Order(conds ...field.Expr) IH1AttendanceDo
	Distinct(cols ...field.Expr) IH1AttendanceDo
	Omit(cols ...field.Expr) IH1AttendanceDo
	Join(table schema.Tabler, on ...field.Expr) IH1AttendanceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1AttendanceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1AttendanceDo
	Group(cols ...field.Expr) IH1AttendanceDo
	Having(conds ...gen.Condition) IH1AttendanceDo
	Limit(limit int) IH1AttendanceDo
	Offset(offset int) IH1AttendanceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1AttendanceDo
	Unscoped() IH1AttendanceDo
	Create(values ...*model.H1Attendance) error
	CreateInBatches(values []*model.H1Attendance, batchSize int) error
	Save(values ...*model.H1Attendance) error
	First() (*model.H1Attendance, error)
	Take() (*model.H1Attendance, error)
	Last() (*model.H1Attendance, error)
	Find() ([]*model.H1Attendance, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Attendance, err error)
	FindInBatches(result *[]*model.H1Attendance, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Attendance) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1AttendanceDo
	Assign(attrs ...field.AssignExpr) IH1AttendanceDo
	Joins(fields ...field.RelationField) IH1AttendanceDo
	Preload(fields ...field.RelationField) IH1AttendanceDo
	FirstOrInit() (*model.H1Attendance, error)
	FirstOrCreate() (*model.H1Attendance, error)
	FindByPage(offset int, limit int) (result []*model.H1Attendance, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1AttendanceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1AttendanceDo) Debug() IH1AttendanceDo {
	return h.withDO(h.DO.Debug())
}

func (h h1AttendanceDo) WithContext(ctx context.Context) IH1AttendanceDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1AttendanceDo) ReadDB() IH1AttendanceDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1AttendanceDo) WriteDB() IH1AttendanceDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1AttendanceDo) Session(config *gorm.Session) IH1AttendanceDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1AttendanceDo) Clauses(conds ...clause.Expression) IH1AttendanceDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1AttendanceDo) Returning(value interface{}, columns ...string) IH1AttendanceDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1AttendanceDo) Not(conds ...gen.Condition) IH1AttendanceDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1AttendanceDo) Or(conds ...gen.Condition) IH1AttendanceDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1AttendanceDo) Select(conds ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1AttendanceDo) Where(conds ...gen.Condition) IH1AttendanceDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1AttendanceDo) Order(conds ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1AttendanceDo) Distinct(cols ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1AttendanceDo) Omit(cols ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1AttendanceDo) Join(table schema.Tabler, on ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1AttendanceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1AttendanceDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1AttendanceDo) Group(cols ...field.Expr) IH1AttendanceDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1AttendanceDo) Having(conds ...gen.Condition) IH1AttendanceDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1AttendanceDo) Limit(limit int) IH1AttendanceDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1AttendanceDo) Offset(offset int) IH1AttendanceDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1AttendanceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1AttendanceDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1AttendanceDo) Unscoped() IH1AttendanceDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1AttendanceDo) Create(values ...*model.H1Attendance) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1AttendanceDo) CreateInBatches(values []*model.H1Attendance, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1AttendanceDo) Save(values ...*model.H1Attendance) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1AttendanceDo) First() (*model.H1Attendance, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Attendance), nil
	}
}

func (h h1AttendanceDo) Take() (*model.H1Attendance, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Attendance), nil
	}
}

func (h h1AttendanceDo) Last() (*model.H1Attendance, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Attendance), nil
	}
}

func (h h1AttendanceDo) Find() ([]*model.H1Attendance, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Attendance), err
}

func (h h1AttendanceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Attendance, err error) {
	buf := make([]*model.H1Attendance, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1AttendanceDo) FindInBatches(result *[]*model.H1Attendance, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1AttendanceDo) Attrs(attrs ...field.AssignExpr) IH1AttendanceDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1AttendanceDo) Assign(attrs ...field.AssignExpr) IH1AttendanceDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1AttendanceDo) Joins(fields ...field.RelationField) IH1AttendanceDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1AttendanceDo) Preload(fields ...field.RelationField) IH1AttendanceDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1AttendanceDo) FirstOrInit() (*model.H1Attendance, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Attendance), nil
	}
}

func (h h1AttendanceDo) FirstOrCreate() (*model.H1Attendance, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Attendance), nil
	}
}

func (h h1AttendanceDo) FindByPage(offset int, limit int) (result []*model.H1Attendance, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1AttendanceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1AttendanceDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1AttendanceDo) Delete(models ...*model.H1Attendance) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1AttendanceDo) withDO(do gen.Dao) *h1AttendanceDo {
	h.DO = *do.(*gen.DO)
	return h
}
