// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"demo/dal/model"
)

func newH1ClassCourse(db *gorm.DB, opts ...gen.DOOption) h1ClassCourse {
	_h1ClassCourse := h1ClassCourse{}

	_h1ClassCourse.h1ClassCourseDo.UseDB(db, opts...)
	_h1ClassCourse.h1ClassCourseDo.UseModel(&model.H1ClassCourse{})

	tableName := _h1ClassCourse.h1ClassCourseDo.TableName()
	_h1ClassCourse.ALL = field.NewAsterisk(tableName)
	_h1ClassCourse.ID = field.NewInt64(tableName, "id")
	_h1ClassCourse.ClassID = field.NewInt64(tableName, "class_id")
	_h1ClassCourse.CourseID = field.NewInt64(tableName, "course_id")
	_h1ClassCourse.SemesterID = field.NewInt64(tableName, "semester_id")
	_h1ClassCourse.PricePerHour = field.NewFloat64(tableName, "price_per_hour")

	_h1ClassCourse.fillFieldMap()

	return _h1ClassCourse
}

type h1ClassCourse struct {
	h1ClassCourseDo h1ClassCourseDo

	ALL          field.Asterisk
	ID           field.Int64
	ClassID      field.Int64
	CourseID     field.Int64
	SemesterID   field.Int64
	PricePerHour field.Float64

	fieldMap map[string]field.Expr
}

func (h h1ClassCourse) Table(newTableName string) *h1ClassCourse {
	h.h1ClassCourseDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1ClassCourse) As(alias string) *h1ClassCourse {
	h.h1ClassCourseDo.DO = *(h.h1ClassCourseDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1ClassCourse) updateTableName(table string) *h1ClassCourse {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.ClassID = field.NewInt64(table, "class_id")
	h.CourseID = field.NewInt64(table, "course_id")
	h.SemesterID = field.NewInt64(table, "semester_id")
	h.PricePerHour = field.NewFloat64(table, "price_per_hour")

	h.fillFieldMap()

	return h
}

func (h *h1ClassCourse) WithContext(ctx context.Context) IH1ClassCourseDo {
	return h.h1ClassCourseDo.WithContext(ctx)
}

func (h h1ClassCourse) TableName() string { return h.h1ClassCourseDo.TableName() }

func (h h1ClassCourse) Alias() string { return h.h1ClassCourseDo.Alias() }

func (h h1ClassCourse) Columns(cols ...field.Expr) gen.Columns {
	return h.h1ClassCourseDo.Columns(cols...)
}

func (h *h1ClassCourse) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1ClassCourse) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 5)
	h.fieldMap["id"] = h.ID
	h.fieldMap["class_id"] = h.ClassID
	h.fieldMap["course_id"] = h.CourseID
	h.fieldMap["semester_id"] = h.SemesterID
	h.fieldMap["price_per_hour"] = h.PricePerHour
}

func (h h1ClassCourse) clone(db *gorm.DB) h1ClassCourse {
	h.h1ClassCourseDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1ClassCourse) replaceDB(db *gorm.DB) h1ClassCourse {
	h.h1ClassCourseDo.ReplaceDB(db)
	return h
}

type h1ClassCourseDo struct{ gen.DO }

type IH1ClassCourseDo interface {
	gen.SubQuery
	Debug() IH1ClassCourseDo
	WithContext(ctx context.Context) IH1ClassCourseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1ClassCourseDo
	WriteDB() IH1ClassCourseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1ClassCourseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1ClassCourseDo
	Not(conds ...gen.Condition) IH1ClassCourseDo
	Or(conds ...gen.Condition) IH1ClassCourseDo
	Select(conds ...field.Expr) IH1ClassCourseDo
	Where(conds ...gen.Condition) IH1ClassCourseDo
	Order(conds ...field.Expr) IH1ClassCourseDo
	Distinct(cols ...field.Expr) IH1ClassCourseDo
	Omit(cols ...field.Expr) IH1ClassCourseDo
	Join(table schema.Tabler, on ...field.Expr) IH1ClassCourseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1ClassCourseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1ClassCourseDo
	Group(cols ...field.Expr) IH1ClassCourseDo
	Having(conds ...gen.Condition) IH1ClassCourseDo
	Limit(limit int) IH1ClassCourseDo
	Offset(offset int) IH1ClassCourseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1ClassCourseDo
	Unscoped() IH1ClassCourseDo
	Create(values ...*model.H1ClassCourse) error
	CreateInBatches(values []*model.H1ClassCourse, batchSize int) error
	Save(values ...*model.H1ClassCourse) error
	First() (*model.H1ClassCourse, error)
	Take() (*model.H1ClassCourse, error)
	Last() (*model.H1ClassCourse, error)
	Find() ([]*model.H1ClassCourse, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1ClassCourse, err error)
	FindInBatches(result *[]*model.H1ClassCourse, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1ClassCourse) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1ClassCourseDo
	Assign(attrs ...field.AssignExpr) IH1ClassCourseDo
	Joins(fields ...field.RelationField) IH1ClassCourseDo
	Preload(fields ...field.RelationField) IH1ClassCourseDo
	FirstOrInit() (*model.H1ClassCourse, error)
	FirstOrCreate() (*model.H1ClassCourse, error)
	FindByPage(offset int, limit int) (result []*model.H1ClassCourse, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1ClassCourseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1ClassCourseDo) Debug() IH1ClassCourseDo {
	return h.withDO(h.DO.Debug())
}

func (h h1ClassCourseDo) WithContext(ctx context.Context) IH1ClassCourseDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1ClassCourseDo) ReadDB() IH1ClassCourseDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1ClassCourseDo) WriteDB() IH1ClassCourseDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1ClassCourseDo) Session(config *gorm.Session) IH1ClassCourseDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1ClassCourseDo) Clauses(conds ...clause.Expression) IH1ClassCourseDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1ClassCourseDo) Returning(value interface{}, columns ...string) IH1ClassCourseDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1ClassCourseDo) Not(conds ...gen.Condition) IH1ClassCourseDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1ClassCourseDo) Or(conds ...gen.Condition) IH1ClassCourseDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1ClassCourseDo) Select(conds ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1ClassCourseDo) Where(conds ...gen.Condition) IH1ClassCourseDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1ClassCourseDo) Order(conds ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1ClassCourseDo) Distinct(cols ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1ClassCourseDo) Omit(cols ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1ClassCourseDo) Join(table schema.Tabler, on ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1ClassCourseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1ClassCourseDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1ClassCourseDo) Group(cols ...field.Expr) IH1ClassCourseDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1ClassCourseDo) Having(conds ...gen.Condition) IH1ClassCourseDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1ClassCourseDo) Limit(limit int) IH1ClassCourseDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1ClassCourseDo) Offset(offset int) IH1ClassCourseDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1ClassCourseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1ClassCourseDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1ClassCourseDo) Unscoped() IH1ClassCourseDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1ClassCourseDo) Create(values ...*model.H1ClassCourse) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1ClassCourseDo) CreateInBatches(values []*model.H1ClassCourse, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1ClassCourseDo) Save(values ...*model.H1ClassCourse) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1ClassCourseDo) First() (*model.H1ClassCourse, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1ClassCourse), nil
	}
}

func (h h1ClassCourseDo) Take() (*model.H1ClassCourse, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1ClassCourse), nil
	}
}

func (h h1ClassCourseDo) Last() (*model.H1ClassCourse, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1ClassCourse), nil
	}
}

func (h h1ClassCourseDo) Find() ([]*model.H1ClassCourse, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1ClassCourse), err
}

func (h h1ClassCourseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1ClassCourse, err error) {
	buf := make([]*model.H1ClassCourse, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1ClassCourseDo) FindInBatches(result *[]*model.H1ClassCourse, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1ClassCourseDo) Attrs(attrs ...field.AssignExpr) IH1ClassCourseDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1ClassCourseDo) Assign(attrs ...field.AssignExpr) IH1ClassCourseDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1ClassCourseDo) Joins(fields ...field.RelationField) IH1ClassCourseDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1ClassCourseDo) Preload(fields ...field.RelationField) IH1ClassCourseDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1ClassCourseDo) FirstOrInit() (*model.H1ClassCourse, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1ClassCourse), nil
	}
}

func (h h1ClassCourseDo) FirstOrCreate() (*model.H1ClassCourse, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1ClassCourse), nil
	}
}

func (h h1ClassCourseDo) FindByPage(offset int, limit int) (result []*model.H1ClassCourse, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1ClassCourseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1ClassCourseDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1ClassCourseDo) Delete(models ...*model.H1ClassCourse) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1ClassCourseDo) withDO(do gen.Dao) *h1ClassCourseDo {
	h.DO = *do.(*gen.DO)
	return h
}
