// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"demo/dal/model"
)

func newH1Course(db *gorm.DB, opts ...gen.DOOption) h1Course {
	_h1Course := h1Course{}

	_h1Course.h1CourseDo.UseDB(db, opts...)
	_h1Course.h1CourseDo.UseModel(&model.H1Course{})

	tableName := _h1Course.h1CourseDo.TableName()
	_h1Course.ALL = field.NewAsterisk(tableName)
	_h1Course.ID = field.NewInt64(tableName, "id")
	_h1Course.Name = field.NewString(tableName, "name")

	_h1Course.fillFieldMap()

	return _h1Course
}

type h1Course struct {
	h1CourseDo h1CourseDo

	ALL  field.Asterisk
	ID   field.Int64
	Name field.String

	fieldMap map[string]field.Expr
}

func (h h1Course) Table(newTableName string) *h1Course {
	h.h1CourseDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Course) As(alias string) *h1Course {
	h.h1CourseDo.DO = *(h.h1CourseDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Course) updateTableName(table string) *h1Course {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Name = field.NewString(table, "name")

	h.fillFieldMap()

	return h
}

func (h *h1Course) WithContext(ctx context.Context) IH1CourseDo { return h.h1CourseDo.WithContext(ctx) }

func (h h1Course) TableName() string { return h.h1CourseDo.TableName() }

func (h h1Course) Alias() string { return h.h1CourseDo.Alias() }

func (h h1Course) Columns(cols ...field.Expr) gen.Columns { return h.h1CourseDo.Columns(cols...) }

func (h *h1Course) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Course) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 2)
	h.fieldMap["id"] = h.ID
	h.fieldMap["name"] = h.Name
}

func (h h1Course) clone(db *gorm.DB) h1Course {
	h.h1CourseDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Course) replaceDB(db *gorm.DB) h1Course {
	h.h1CourseDo.ReplaceDB(db)
	return h
}

type h1CourseDo struct{ gen.DO }

type IH1CourseDo interface {
	gen.SubQuery
	Debug() IH1CourseDo
	WithContext(ctx context.Context) IH1CourseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1CourseDo
	WriteDB() IH1CourseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1CourseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1CourseDo
	Not(conds ...gen.Condition) IH1CourseDo
	Or(conds ...gen.Condition) IH1CourseDo
	Select(conds ...field.Expr) IH1CourseDo
	Where(conds ...gen.Condition) IH1CourseDo
	Order(conds ...field.Expr) IH1CourseDo
	Distinct(cols ...field.Expr) IH1CourseDo
	Omit(cols ...field.Expr) IH1CourseDo
	Join(table schema.Tabler, on ...field.Expr) IH1CourseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1CourseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1CourseDo
	Group(cols ...field.Expr) IH1CourseDo
	Having(conds ...gen.Condition) IH1CourseDo
	Limit(limit int) IH1CourseDo
	Offset(offset int) IH1CourseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1CourseDo
	Unscoped() IH1CourseDo
	Create(values ...*model.H1Course) error
	CreateInBatches(values []*model.H1Course, batchSize int) error
	Save(values ...*model.H1Course) error
	First() (*model.H1Course, error)
	Take() (*model.H1Course, error)
	Last() (*model.H1Course, error)
	Find() ([]*model.H1Course, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Course, err error)
	FindInBatches(result *[]*model.H1Course, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Course) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1CourseDo
	Assign(attrs ...field.AssignExpr) IH1CourseDo
	Joins(fields ...field.RelationField) IH1CourseDo
	Preload(fields ...field.RelationField) IH1CourseDo
	FirstOrInit() (*model.H1Course, error)
	FirstOrCreate() (*model.H1Course, error)
	FindByPage(offset int, limit int) (result []*model.H1Course, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1CourseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1CourseDo) Debug() IH1CourseDo {
	return h.withDO(h.DO.Debug())
}

func (h h1CourseDo) WithContext(ctx context.Context) IH1CourseDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1CourseDo) ReadDB() IH1CourseDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1CourseDo) WriteDB() IH1CourseDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1CourseDo) Session(config *gorm.Session) IH1CourseDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1CourseDo) Clauses(conds ...clause.Expression) IH1CourseDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1CourseDo) Returning(value interface{}, columns ...string) IH1CourseDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1CourseDo) Not(conds ...gen.Condition) IH1CourseDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1CourseDo) Or(conds ...gen.Condition) IH1CourseDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1CourseDo) Select(conds ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1CourseDo) Where(conds ...gen.Condition) IH1CourseDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1CourseDo) Order(conds ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1CourseDo) Distinct(cols ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1CourseDo) Omit(cols ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1CourseDo) Join(table schema.Tabler, on ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1CourseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1CourseDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1CourseDo) Group(cols ...field.Expr) IH1CourseDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1CourseDo) Having(conds ...gen.Condition) IH1CourseDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1CourseDo) Limit(limit int) IH1CourseDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1CourseDo) Offset(offset int) IH1CourseDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1CourseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1CourseDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1CourseDo) Unscoped() IH1CourseDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1CourseDo) Create(values ...*model.H1Course) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1CourseDo) CreateInBatches(values []*model.H1Course, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1CourseDo) Save(values ...*model.H1Course) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1CourseDo) First() (*model.H1Course, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Course), nil
	}
}

func (h h1CourseDo) Take() (*model.H1Course, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Course), nil
	}
}

func (h h1CourseDo) Last() (*model.H1Course, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Course), nil
	}
}

func (h h1CourseDo) Find() ([]*model.H1Course, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Course), err
}

func (h h1CourseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Course, err error) {
	buf := make([]*model.H1Course, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1CourseDo) FindInBatches(result *[]*model.H1Course, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1CourseDo) Attrs(attrs ...field.AssignExpr) IH1CourseDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1CourseDo) Assign(attrs ...field.AssignExpr) IH1CourseDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1CourseDo) Joins(fields ...field.RelationField) IH1CourseDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1CourseDo) Preload(fields ...field.RelationField) IH1CourseDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1CourseDo) FirstOrInit() (*model.H1Course, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Course), nil
	}
}

func (h h1CourseDo) FirstOrCreate() (*model.H1Course, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Course), nil
	}
}

func (h h1CourseDo) FindByPage(offset int, limit int) (result []*model.H1Course, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1CourseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1CourseDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1CourseDo) Delete(models ...*model.H1Course) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1CourseDo) withDO(do gen.Dao) *h1CourseDo {
	h.DO = *do.(*gen.DO)
	return h
}
