// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"demo/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newH1Class(db *gorm.DB, opts ...gen.DOOption) h1Class {
	_h1Class := h1Class{}

	_h1Class.h1ClassDo.UseDB(db, opts...)
	_h1Class.h1ClassDo.UseModel(&model.H1Class{})

	tableName := _h1Class.h1ClassDo.TableName()
	_h1Class.ALL = field.NewAsterisk(tableName)
	_h1Class.ID = field.NewInt64(tableName, "id")
	_h1Class.Name = field.NewString(tableName, "name")
	_h1Class.SemesterID = field.NewInt64(tableName, "semester_id")

	_h1Class.fillFieldMap()

	return _h1Class
}

type h1Class struct {
	h1ClassDo h1ClassDo

	ALL        field.Asterisk
	ID         field.Int64
	Name       field.String
	SemesterID field.Int64

	fieldMap map[string]field.Expr
}

func (h h1Class) Table(newTableName string) *h1Class {
	h.h1ClassDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Class) As(alias string) *h1Class {
	h.h1ClassDo.DO = *(h.h1ClassDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Class) updateTableName(table string) *h1Class {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Name = field.NewString(table, "name")
	h.SemesterID = field.NewInt64(table, "semester_id")

	h.fillFieldMap()

	return h
}

func (h *h1Class) WithContext(ctx context.Context) IH1ClassDo { return h.h1ClassDo.WithContext(ctx) }

func (h h1Class) TableName() string { return h.h1ClassDo.TableName() }

func (h h1Class) Alias() string { return h.h1ClassDo.Alias() }

func (h h1Class) Columns(cols ...field.Expr) gen.Columns { return h.h1ClassDo.Columns(cols...) }

func (h *h1Class) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Class) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 3)
	h.fieldMap["id"] = h.ID
	h.fieldMap["name"] = h.Name
	h.fieldMap["semester_id"] = h.SemesterID
}

func (h h1Class) clone(db *gorm.DB) h1Class {
	h.h1ClassDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Class) replaceDB(db *gorm.DB) h1Class {
	h.h1ClassDo.ReplaceDB(db)
	return h
}

type h1ClassDo struct{ gen.DO }

type IH1ClassDo interface {
	gen.SubQuery
	Debug() IH1ClassDo
	WithContext(ctx context.Context) IH1ClassDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1ClassDo
	WriteDB() IH1ClassDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1ClassDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1ClassDo
	Not(conds ...gen.Condition) IH1ClassDo
	Or(conds ...gen.Condition) IH1ClassDo
	Select(conds ...field.Expr) IH1ClassDo
	Where(conds ...gen.Condition) IH1ClassDo
	Order(conds ...field.Expr) IH1ClassDo
	Distinct(cols ...field.Expr) IH1ClassDo
	Omit(cols ...field.Expr) IH1ClassDo
	Join(table schema.Tabler, on ...field.Expr) IH1ClassDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1ClassDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1ClassDo
	Group(cols ...field.Expr) IH1ClassDo
	Having(conds ...gen.Condition) IH1ClassDo
	Limit(limit int) IH1ClassDo
	Offset(offset int) IH1ClassDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1ClassDo
	Unscoped() IH1ClassDo
	Create(values ...*model.H1Class) error
	CreateInBatches(values []*model.H1Class, batchSize int) error
	Save(values ...*model.H1Class) error
	First() (*model.H1Class, error)
	Take() (*model.H1Class, error)
	Last() (*model.H1Class, error)
	Find() ([]*model.H1Class, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Class, err error)
	FindInBatches(result *[]*model.H1Class, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Class) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1ClassDo
	Assign(attrs ...field.AssignExpr) IH1ClassDo
	Joins(fields ...field.RelationField) IH1ClassDo
	Preload(fields ...field.RelationField) IH1ClassDo
	FirstOrInit() (*model.H1Class, error)
	FirstOrCreate() (*model.H1Class, error)
	FindByPage(offset int, limit int) (result []*model.H1Class, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1ClassDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1ClassDo) Debug() IH1ClassDo {
	return h.withDO(h.DO.Debug())
}

func (h h1ClassDo) WithContext(ctx context.Context) IH1ClassDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1ClassDo) ReadDB() IH1ClassDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1ClassDo) WriteDB() IH1ClassDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1ClassDo) Session(config *gorm.Session) IH1ClassDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1ClassDo) Clauses(conds ...clause.Expression) IH1ClassDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1ClassDo) Returning(value interface{}, columns ...string) IH1ClassDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1ClassDo) Not(conds ...gen.Condition) IH1ClassDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1ClassDo) Or(conds ...gen.Condition) IH1ClassDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1ClassDo) Select(conds ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1ClassDo) Where(conds ...gen.Condition) IH1ClassDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1ClassDo) Order(conds ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1ClassDo) Distinct(cols ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1ClassDo) Omit(cols ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1ClassDo) Join(table schema.Tabler, on ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1ClassDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1ClassDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1ClassDo) Group(cols ...field.Expr) IH1ClassDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1ClassDo) Having(conds ...gen.Condition) IH1ClassDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1ClassDo) Limit(limit int) IH1ClassDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1ClassDo) Offset(offset int) IH1ClassDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1ClassDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1ClassDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1ClassDo) Unscoped() IH1ClassDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1ClassDo) Create(values ...*model.H1Class) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1ClassDo) CreateInBatches(values []*model.H1Class, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1ClassDo) Save(values ...*model.H1Class) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1ClassDo) First() (*model.H1Class, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Class), nil
	}
}

func (h h1ClassDo) Take() (*model.H1Class, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Class), nil
	}
}

func (h h1ClassDo) Last() (*model.H1Class, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Class), nil
	}
}

func (h h1ClassDo) Find() ([]*model.H1Class, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Class), err
}

func (h h1ClassDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Class, err error) {
	buf := make([]*model.H1Class, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1ClassDo) FindInBatches(result *[]*model.H1Class, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1ClassDo) Attrs(attrs ...field.AssignExpr) IH1ClassDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1ClassDo) Assign(attrs ...field.AssignExpr) IH1ClassDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1ClassDo) Joins(fields ...field.RelationField) IH1ClassDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1ClassDo) Preload(fields ...field.RelationField) IH1ClassDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1ClassDo) FirstOrInit() (*model.H1Class, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Class), nil
	}
}

func (h h1ClassDo) FirstOrCreate() (*model.H1Class, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Class), nil
	}
}

func (h h1ClassDo) FindByPage(offset int, limit int) (result []*model.H1Class, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1ClassDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1ClassDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1ClassDo) Delete(models ...*model.H1Class) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1ClassDo) withDO(do gen.Dao) *h1ClassDo {
	h.DO = *do.(*gen.DO)
	return h
}
