// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"demo/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newH1Enrollment(db *gorm.DB, opts ...gen.DOOption) h1Enrollment {
	_h1Enrollment := h1Enrollment{}

	_h1Enrollment.h1EnrollmentDo.UseDB(db, opts...)
	_h1Enrollment.h1EnrollmentDo.UseModel(&model.H1Enrollment{})

	tableName := _h1Enrollment.h1EnrollmentDo.TableName()
	_h1Enrollment.ALL = field.NewAsterisk(tableName)
	_h1Enrollment.ID = field.NewInt64(tableName, "id")
	_h1Enrollment.StudentID = field.NewInt64(tableName, "student_id")
	_h1Enrollment.ClassCourseID = field.NewInt64(tableName, "class_course_id")
	_h1Enrollment.EnrolledAt = field.NewTime(tableName, "enrolled_at")

	_h1Enrollment.fillFieldMap()

	return _h1Enrollment
}

type h1Enrollment struct {
	h1EnrollmentDo h1EnrollmentDo

	ALL           field.Asterisk
	ID            field.Int64
	StudentID     field.Int64
	ClassCourseID field.Int64
	EnrolledAt    field.Time

	fieldMap map[string]field.Expr
}

func (h h1Enrollment) Table(newTableName string) *h1Enrollment {
	h.h1EnrollmentDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Enrollment) As(alias string) *h1Enrollment {
	h.h1EnrollmentDo.DO = *(h.h1EnrollmentDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Enrollment) updateTableName(table string) *h1Enrollment {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.StudentID = field.NewInt64(table, "student_id")
	h.ClassCourseID = field.NewInt64(table, "class_course_id")
	h.EnrolledAt = field.NewTime(table, "enrolled_at")

	h.fillFieldMap()

	return h
}

func (h *h1Enrollment) WithContext(ctx context.Context) IH1EnrollmentDo {
	return h.h1EnrollmentDo.WithContext(ctx)
}

func (h h1Enrollment) TableName() string { return h.h1EnrollmentDo.TableName() }

func (h h1Enrollment) Alias() string { return h.h1EnrollmentDo.Alias() }

func (h h1Enrollment) Columns(cols ...field.Expr) gen.Columns {
	return h.h1EnrollmentDo.Columns(cols...)
}

func (h *h1Enrollment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Enrollment) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 4)
	h.fieldMap["id"] = h.ID
	h.fieldMap["student_id"] = h.StudentID
	h.fieldMap["class_course_id"] = h.ClassCourseID
	h.fieldMap["enrolled_at"] = h.EnrolledAt
}

func (h h1Enrollment) clone(db *gorm.DB) h1Enrollment {
	h.h1EnrollmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Enrollment) replaceDB(db *gorm.DB) h1Enrollment {
	h.h1EnrollmentDo.ReplaceDB(db)
	return h
}

type h1EnrollmentDo struct{ gen.DO }

type IH1EnrollmentDo interface {
	gen.SubQuery
	Debug() IH1EnrollmentDo
	WithContext(ctx context.Context) IH1EnrollmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1EnrollmentDo
	WriteDB() IH1EnrollmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1EnrollmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1EnrollmentDo
	Not(conds ...gen.Condition) IH1EnrollmentDo
	Or(conds ...gen.Condition) IH1EnrollmentDo
	Select(conds ...field.Expr) IH1EnrollmentDo
	Where(conds ...gen.Condition) IH1EnrollmentDo
	Order(conds ...field.Expr) IH1EnrollmentDo
	Distinct(cols ...field.Expr) IH1EnrollmentDo
	Omit(cols ...field.Expr) IH1EnrollmentDo
	Join(table schema.Tabler, on ...field.Expr) IH1EnrollmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1EnrollmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1EnrollmentDo
	Group(cols ...field.Expr) IH1EnrollmentDo
	Having(conds ...gen.Condition) IH1EnrollmentDo
	Limit(limit int) IH1EnrollmentDo
	Offset(offset int) IH1EnrollmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1EnrollmentDo
	Unscoped() IH1EnrollmentDo
	Create(values ...*model.H1Enrollment) error
	CreateInBatches(values []*model.H1Enrollment, batchSize int) error
	Save(values ...*model.H1Enrollment) error
	First() (*model.H1Enrollment, error)
	Take() (*model.H1Enrollment, error)
	Last() (*model.H1Enrollment, error)
	Find() ([]*model.H1Enrollment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Enrollment, err error)
	FindInBatches(result *[]*model.H1Enrollment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Enrollment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1EnrollmentDo
	Assign(attrs ...field.AssignExpr) IH1EnrollmentDo
	Joins(fields ...field.RelationField) IH1EnrollmentDo
	Preload(fields ...field.RelationField) IH1EnrollmentDo
	FirstOrInit() (*model.H1Enrollment, error)
	FirstOrCreate() (*model.H1Enrollment, error)
	FindByPage(offset int, limit int) (result []*model.H1Enrollment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1EnrollmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1EnrollmentDo) Debug() IH1EnrollmentDo {
	return h.withDO(h.DO.Debug())
}

func (h h1EnrollmentDo) WithContext(ctx context.Context) IH1EnrollmentDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1EnrollmentDo) ReadDB() IH1EnrollmentDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1EnrollmentDo) WriteDB() IH1EnrollmentDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1EnrollmentDo) Session(config *gorm.Session) IH1EnrollmentDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1EnrollmentDo) Clauses(conds ...clause.Expression) IH1EnrollmentDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1EnrollmentDo) Returning(value interface{}, columns ...string) IH1EnrollmentDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1EnrollmentDo) Not(conds ...gen.Condition) IH1EnrollmentDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1EnrollmentDo) Or(conds ...gen.Condition) IH1EnrollmentDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1EnrollmentDo) Select(conds ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1EnrollmentDo) Where(conds ...gen.Condition) IH1EnrollmentDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1EnrollmentDo) Order(conds ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1EnrollmentDo) Distinct(cols ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1EnrollmentDo) Omit(cols ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1EnrollmentDo) Join(table schema.Tabler, on ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1EnrollmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1EnrollmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1EnrollmentDo) Group(cols ...field.Expr) IH1EnrollmentDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1EnrollmentDo) Having(conds ...gen.Condition) IH1EnrollmentDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1EnrollmentDo) Limit(limit int) IH1EnrollmentDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1EnrollmentDo) Offset(offset int) IH1EnrollmentDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1EnrollmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1EnrollmentDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1EnrollmentDo) Unscoped() IH1EnrollmentDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1EnrollmentDo) Create(values ...*model.H1Enrollment) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1EnrollmentDo) CreateInBatches(values []*model.H1Enrollment, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1EnrollmentDo) Save(values ...*model.H1Enrollment) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1EnrollmentDo) First() (*model.H1Enrollment, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Enrollment), nil
	}
}

func (h h1EnrollmentDo) Take() (*model.H1Enrollment, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Enrollment), nil
	}
}

func (h h1EnrollmentDo) Last() (*model.H1Enrollment, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Enrollment), nil
	}
}

func (h h1EnrollmentDo) Find() ([]*model.H1Enrollment, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Enrollment), err
}

func (h h1EnrollmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Enrollment, err error) {
	buf := make([]*model.H1Enrollment, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1EnrollmentDo) FindInBatches(result *[]*model.H1Enrollment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1EnrollmentDo) Attrs(attrs ...field.AssignExpr) IH1EnrollmentDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1EnrollmentDo) Assign(attrs ...field.AssignExpr) IH1EnrollmentDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1EnrollmentDo) Joins(fields ...field.RelationField) IH1EnrollmentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1EnrollmentDo) Preload(fields ...field.RelationField) IH1EnrollmentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1EnrollmentDo) FirstOrInit() (*model.H1Enrollment, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Enrollment), nil
	}
}

func (h h1EnrollmentDo) FirstOrCreate() (*model.H1Enrollment, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Enrollment), nil
	}
}

func (h h1EnrollmentDo) FindByPage(offset int, limit int) (result []*model.H1Enrollment, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1EnrollmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1EnrollmentDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1EnrollmentDo) Delete(models ...*model.H1Enrollment) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1EnrollmentDo) withDO(do gen.Dao) *h1EnrollmentDo {
	h.DO = *do.(*gen.DO)
	return h
}
