// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"demo/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newH1Schedule(db *gorm.DB, opts ...gen.DOOption) h1Schedule {
	_h1Schedule := h1Schedule{}

	_h1Schedule.h1ScheduleDo.UseDB(db, opts...)
	_h1Schedule.h1ScheduleDo.UseModel(&model.H1Schedule{})

	tableName := _h1Schedule.h1ScheduleDo.TableName()
	_h1Schedule.ALL = field.NewAsterisk(tableName)
	_h1Schedule.ID = field.NewInt64(tableName, "id")
	_h1Schedule.ClassCourseID = field.NewInt64(tableName, "class_course_id")
	_h1Schedule.Date = field.NewTime(tableName, "date")
	_h1Schedule.StartTime = field.NewTime(tableName, "start_time")
	_h1Schedule.EndTime = field.NewTime(tableName, "end_time")

	_h1Schedule.fillFieldMap()

	return _h1Schedule
}

type h1Schedule struct {
	h1ScheduleDo h1ScheduleDo

	ALL           field.Asterisk
	ID            field.Int64
	ClassCourseID field.Int64
	Date          field.Time
	StartTime     field.Time
	EndTime       field.Time

	fieldMap map[string]field.Expr
}

func (h h1Schedule) Table(newTableName string) *h1Schedule {
	h.h1ScheduleDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Schedule) As(alias string) *h1Schedule {
	h.h1ScheduleDo.DO = *(h.h1ScheduleDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Schedule) updateTableName(table string) *h1Schedule {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.ClassCourseID = field.NewInt64(table, "class_course_id")
	h.Date = field.NewTime(table, "date")
	h.StartTime = field.NewTime(table, "start_time")
	h.EndTime = field.NewTime(table, "end_time")

	h.fillFieldMap()

	return h
}

func (h *h1Schedule) WithContext(ctx context.Context) IH1ScheduleDo {
	return h.h1ScheduleDo.WithContext(ctx)
}

func (h h1Schedule) TableName() string { return h.h1ScheduleDo.TableName() }

func (h h1Schedule) Alias() string { return h.h1ScheduleDo.Alias() }

func (h h1Schedule) Columns(cols ...field.Expr) gen.Columns { return h.h1ScheduleDo.Columns(cols...) }

func (h *h1Schedule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Schedule) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 5)
	h.fieldMap["id"] = h.ID
	h.fieldMap["class_course_id"] = h.ClassCourseID
	h.fieldMap["date"] = h.Date
	h.fieldMap["start_time"] = h.StartTime
	h.fieldMap["end_time"] = h.EndTime
}

func (h h1Schedule) clone(db *gorm.DB) h1Schedule {
	h.h1ScheduleDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Schedule) replaceDB(db *gorm.DB) h1Schedule {
	h.h1ScheduleDo.ReplaceDB(db)
	return h
}

type h1ScheduleDo struct{ gen.DO }

type IH1ScheduleDo interface {
	gen.SubQuery
	Debug() IH1ScheduleDo
	WithContext(ctx context.Context) IH1ScheduleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1ScheduleDo
	WriteDB() IH1ScheduleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1ScheduleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1ScheduleDo
	Not(conds ...gen.Condition) IH1ScheduleDo
	Or(conds ...gen.Condition) IH1ScheduleDo
	Select(conds ...field.Expr) IH1ScheduleDo
	Where(conds ...gen.Condition) IH1ScheduleDo
	Order(conds ...field.Expr) IH1ScheduleDo
	Distinct(cols ...field.Expr) IH1ScheduleDo
	Omit(cols ...field.Expr) IH1ScheduleDo
	Join(table schema.Tabler, on ...field.Expr) IH1ScheduleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1ScheduleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1ScheduleDo
	Group(cols ...field.Expr) IH1ScheduleDo
	Having(conds ...gen.Condition) IH1ScheduleDo
	Limit(limit int) IH1ScheduleDo
	Offset(offset int) IH1ScheduleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1ScheduleDo
	Unscoped() IH1ScheduleDo
	Create(values ...*model.H1Schedule) error
	CreateInBatches(values []*model.H1Schedule, batchSize int) error
	Save(values ...*model.H1Schedule) error
	First() (*model.H1Schedule, error)
	Take() (*model.H1Schedule, error)
	Last() (*model.H1Schedule, error)
	Find() ([]*model.H1Schedule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Schedule, err error)
	FindInBatches(result *[]*model.H1Schedule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Schedule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1ScheduleDo
	Assign(attrs ...field.AssignExpr) IH1ScheduleDo
	Joins(fields ...field.RelationField) IH1ScheduleDo
	Preload(fields ...field.RelationField) IH1ScheduleDo
	FirstOrInit() (*model.H1Schedule, error)
	FirstOrCreate() (*model.H1Schedule, error)
	FindByPage(offset int, limit int) (result []*model.H1Schedule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1ScheduleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1ScheduleDo) Debug() IH1ScheduleDo {
	return h.withDO(h.DO.Debug())
}

func (h h1ScheduleDo) WithContext(ctx context.Context) IH1ScheduleDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1ScheduleDo) ReadDB() IH1ScheduleDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1ScheduleDo) WriteDB() IH1ScheduleDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1ScheduleDo) Session(config *gorm.Session) IH1ScheduleDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1ScheduleDo) Clauses(conds ...clause.Expression) IH1ScheduleDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1ScheduleDo) Returning(value interface{}, columns ...string) IH1ScheduleDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1ScheduleDo) Not(conds ...gen.Condition) IH1ScheduleDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1ScheduleDo) Or(conds ...gen.Condition) IH1ScheduleDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1ScheduleDo) Select(conds ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1ScheduleDo) Where(conds ...gen.Condition) IH1ScheduleDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1ScheduleDo) Order(conds ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1ScheduleDo) Distinct(cols ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1ScheduleDo) Omit(cols ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1ScheduleDo) Join(table schema.Tabler, on ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1ScheduleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1ScheduleDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1ScheduleDo) Group(cols ...field.Expr) IH1ScheduleDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1ScheduleDo) Having(conds ...gen.Condition) IH1ScheduleDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1ScheduleDo) Limit(limit int) IH1ScheduleDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1ScheduleDo) Offset(offset int) IH1ScheduleDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1ScheduleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1ScheduleDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1ScheduleDo) Unscoped() IH1ScheduleDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1ScheduleDo) Create(values ...*model.H1Schedule) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1ScheduleDo) CreateInBatches(values []*model.H1Schedule, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1ScheduleDo) Save(values ...*model.H1Schedule) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1ScheduleDo) First() (*model.H1Schedule, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Schedule), nil
	}
}

func (h h1ScheduleDo) Take() (*model.H1Schedule, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Schedule), nil
	}
}

func (h h1ScheduleDo) Last() (*model.H1Schedule, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Schedule), nil
	}
}

func (h h1ScheduleDo) Find() ([]*model.H1Schedule, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Schedule), err
}

func (h h1ScheduleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Schedule, err error) {
	buf := make([]*model.H1Schedule, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1ScheduleDo) FindInBatches(result *[]*model.H1Schedule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1ScheduleDo) Attrs(attrs ...field.AssignExpr) IH1ScheduleDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1ScheduleDo) Assign(attrs ...field.AssignExpr) IH1ScheduleDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1ScheduleDo) Joins(fields ...field.RelationField) IH1ScheduleDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1ScheduleDo) Preload(fields ...field.RelationField) IH1ScheduleDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1ScheduleDo) FirstOrInit() (*model.H1Schedule, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Schedule), nil
	}
}

func (h h1ScheduleDo) FirstOrCreate() (*model.H1Schedule, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Schedule), nil
	}
}

func (h h1ScheduleDo) FindByPage(offset int, limit int) (result []*model.H1Schedule, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1ScheduleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1ScheduleDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1ScheduleDo) Delete(models ...*model.H1Schedule) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1ScheduleDo) withDO(do gen.Dao) *h1ScheduleDo {
	h.DO = *do.(*gen.DO)
	return h
}
