// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"demo/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newH1Semester(db *gorm.DB, opts ...gen.DOOption) h1Semester {
	_h1Semester := h1Semester{}

	_h1Semester.h1SemesterDo.UseDB(db, opts...)
	_h1Semester.h1SemesterDo.UseModel(&model.H1Semester{})

	tableName := _h1Semester.h1SemesterDo.TableName()
	_h1Semester.ALL = field.NewAsterisk(tableName)
	_h1Semester.ID = field.NewInt64(tableName, "id")
	_h1Semester.Name = field.NewString(tableName, "name")
	_h1Semester.StartDate = field.NewTime(tableName, "start_date")
	_h1Semester.EndDate = field.NewTime(tableName, "end_date")

	_h1Semester.fillFieldMap()

	return _h1Semester
}

type h1Semester struct {
	h1SemesterDo h1SemesterDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	StartDate field.Time
	EndDate   field.Time

	fieldMap map[string]field.Expr
}

func (h h1Semester) Table(newTableName string) *h1Semester {
	h.h1SemesterDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Semester) As(alias string) *h1Semester {
	h.h1SemesterDo.DO = *(h.h1SemesterDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Semester) updateTableName(table string) *h1Semester {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Name = field.NewString(table, "name")
	h.StartDate = field.NewTime(table, "start_date")
	h.EndDate = field.NewTime(table, "end_date")

	h.fillFieldMap()

	return h
}

func (h *h1Semester) WithContext(ctx context.Context) IH1SemesterDo {
	return h.h1SemesterDo.WithContext(ctx)
}

func (h h1Semester) TableName() string { return h.h1SemesterDo.TableName() }

func (h h1Semester) Alias() string { return h.h1SemesterDo.Alias() }

func (h h1Semester) Columns(cols ...field.Expr) gen.Columns { return h.h1SemesterDo.Columns(cols...) }

func (h *h1Semester) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Semester) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 4)
	h.fieldMap["id"] = h.ID
	h.fieldMap["name"] = h.Name
	h.fieldMap["start_date"] = h.StartDate
	h.fieldMap["end_date"] = h.EndDate
}

func (h h1Semester) clone(db *gorm.DB) h1Semester {
	h.h1SemesterDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Semester) replaceDB(db *gorm.DB) h1Semester {
	h.h1SemesterDo.ReplaceDB(db)
	return h
}

type h1SemesterDo struct{ gen.DO }

type IH1SemesterDo interface {
	gen.SubQuery
	Debug() IH1SemesterDo
	WithContext(ctx context.Context) IH1SemesterDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1SemesterDo
	WriteDB() IH1SemesterDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1SemesterDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1SemesterDo
	Not(conds ...gen.Condition) IH1SemesterDo
	Or(conds ...gen.Condition) IH1SemesterDo
	Select(conds ...field.Expr) IH1SemesterDo
	Where(conds ...gen.Condition) IH1SemesterDo
	Order(conds ...field.Expr) IH1SemesterDo
	Distinct(cols ...field.Expr) IH1SemesterDo
	Omit(cols ...field.Expr) IH1SemesterDo
	Join(table schema.Tabler, on ...field.Expr) IH1SemesterDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1SemesterDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1SemesterDo
	Group(cols ...field.Expr) IH1SemesterDo
	Having(conds ...gen.Condition) IH1SemesterDo
	Limit(limit int) IH1SemesterDo
	Offset(offset int) IH1SemesterDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1SemesterDo
	Unscoped() IH1SemesterDo
	Create(values ...*model.H1Semester) error
	CreateInBatches(values []*model.H1Semester, batchSize int) error
	Save(values ...*model.H1Semester) error
	First() (*model.H1Semester, error)
	Take() (*model.H1Semester, error)
	Last() (*model.H1Semester, error)
	Find() ([]*model.H1Semester, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Semester, err error)
	FindInBatches(result *[]*model.H1Semester, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Semester) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1SemesterDo
	Assign(attrs ...field.AssignExpr) IH1SemesterDo
	Joins(fields ...field.RelationField) IH1SemesterDo
	Preload(fields ...field.RelationField) IH1SemesterDo
	FirstOrInit() (*model.H1Semester, error)
	FirstOrCreate() (*model.H1Semester, error)
	FindByPage(offset int, limit int) (result []*model.H1Semester, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1SemesterDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1SemesterDo) Debug() IH1SemesterDo {
	return h.withDO(h.DO.Debug())
}

func (h h1SemesterDo) WithContext(ctx context.Context) IH1SemesterDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1SemesterDo) ReadDB() IH1SemesterDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1SemesterDo) WriteDB() IH1SemesterDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1SemesterDo) Session(config *gorm.Session) IH1SemesterDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1SemesterDo) Clauses(conds ...clause.Expression) IH1SemesterDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1SemesterDo) Returning(value interface{}, columns ...string) IH1SemesterDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1SemesterDo) Not(conds ...gen.Condition) IH1SemesterDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1SemesterDo) Or(conds ...gen.Condition) IH1SemesterDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1SemesterDo) Select(conds ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1SemesterDo) Where(conds ...gen.Condition) IH1SemesterDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1SemesterDo) Order(conds ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1SemesterDo) Distinct(cols ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1SemesterDo) Omit(cols ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1SemesterDo) Join(table schema.Tabler, on ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1SemesterDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1SemesterDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1SemesterDo) Group(cols ...field.Expr) IH1SemesterDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1SemesterDo) Having(conds ...gen.Condition) IH1SemesterDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1SemesterDo) Limit(limit int) IH1SemesterDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1SemesterDo) Offset(offset int) IH1SemesterDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1SemesterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1SemesterDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1SemesterDo) Unscoped() IH1SemesterDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1SemesterDo) Create(values ...*model.H1Semester) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1SemesterDo) CreateInBatches(values []*model.H1Semester, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1SemesterDo) Save(values ...*model.H1Semester) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1SemesterDo) First() (*model.H1Semester, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Semester), nil
	}
}

func (h h1SemesterDo) Take() (*model.H1Semester, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Semester), nil
	}
}

func (h h1SemesterDo) Last() (*model.H1Semester, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Semester), nil
	}
}

func (h h1SemesterDo) Find() ([]*model.H1Semester, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Semester), err
}

func (h h1SemesterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Semester, err error) {
	buf := make([]*model.H1Semester, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1SemesterDo) FindInBatches(result *[]*model.H1Semester, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1SemesterDo) Attrs(attrs ...field.AssignExpr) IH1SemesterDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1SemesterDo) Assign(attrs ...field.AssignExpr) IH1SemesterDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1SemesterDo) Joins(fields ...field.RelationField) IH1SemesterDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1SemesterDo) Preload(fields ...field.RelationField) IH1SemesterDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1SemesterDo) FirstOrInit() (*model.H1Semester, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Semester), nil
	}
}

func (h h1SemesterDo) FirstOrCreate() (*model.H1Semester, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Semester), nil
	}
}

func (h h1SemesterDo) FindByPage(offset int, limit int) (result []*model.H1Semester, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1SemesterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1SemesterDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1SemesterDo) Delete(models ...*model.H1Semester) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1SemesterDo) withDO(do gen.Dao) *h1SemesterDo {
	h.DO = *do.(*gen.DO)
	return h
}
