// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"demo/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newH1StudentSemesterBill(db *gorm.DB, opts ...gen.DOOption) h1StudentSemesterBill {
	_h1StudentSemesterBill := h1StudentSemesterBill{}

	_h1StudentSemesterBill.h1StudentSemesterBillDo.UseDB(db, opts...)
	_h1StudentSemesterBill.h1StudentSemesterBillDo.UseModel(&model.H1StudentSemesterBill{})

	tableName := _h1StudentSemesterBill.h1StudentSemesterBillDo.TableName()
	_h1StudentSemesterBill.ALL = field.NewAsterisk(tableName)
	_h1StudentSemesterBill.ID = field.NewInt64(tableName, "id")
	_h1StudentSemesterBill.StudentID = field.NewInt64(tableName, "student_id")
	_h1StudentSemesterBill.SemesterID = field.NewInt64(tableName, "semester_id")
	_h1StudentSemesterBill.TotalFee = field.NewFloat64(tableName, "total_fee")
	_h1StudentSemesterBill.FinalizedAt = field.NewTime(tableName, "finalized_at")
	_h1StudentSemesterBill.Status = field.NewString(tableName, "status")

	_h1StudentSemesterBill.fillFieldMap()

	return _h1StudentSemesterBill
}

type h1StudentSemesterBill struct {
	h1StudentSemesterBillDo h1StudentSemesterBillDo

	ALL         field.Asterisk
	ID          field.Int64
	StudentID   field.Int64
	SemesterID  field.Int64
	TotalFee    field.Float64
	FinalizedAt field.Time
	Status      field.String

	fieldMap map[string]field.Expr
}

func (h h1StudentSemesterBill) Table(newTableName string) *h1StudentSemesterBill {
	h.h1StudentSemesterBillDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1StudentSemesterBill) As(alias string) *h1StudentSemesterBill {
	h.h1StudentSemesterBillDo.DO = *(h.h1StudentSemesterBillDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1StudentSemesterBill) updateTableName(table string) *h1StudentSemesterBill {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.StudentID = field.NewInt64(table, "student_id")
	h.SemesterID = field.NewInt64(table, "semester_id")
	h.TotalFee = field.NewFloat64(table, "total_fee")
	h.FinalizedAt = field.NewTime(table, "finalized_at")
	h.Status = field.NewString(table, "status")

	h.fillFieldMap()

	return h
}

func (h *h1StudentSemesterBill) WithContext(ctx context.Context) IH1StudentSemesterBillDo {
	return h.h1StudentSemesterBillDo.WithContext(ctx)
}

func (h h1StudentSemesterBill) TableName() string { return h.h1StudentSemesterBillDo.TableName() }

func (h h1StudentSemesterBill) Alias() string { return h.h1StudentSemesterBillDo.Alias() }

func (h h1StudentSemesterBill) Columns(cols ...field.Expr) gen.Columns {
	return h.h1StudentSemesterBillDo.Columns(cols...)
}

func (h *h1StudentSemesterBill) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1StudentSemesterBill) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 6)
	h.fieldMap["id"] = h.ID
	h.fieldMap["student_id"] = h.StudentID
	h.fieldMap["semester_id"] = h.SemesterID
	h.fieldMap["total_fee"] = h.TotalFee
	h.fieldMap["finalized_at"] = h.FinalizedAt
	h.fieldMap["status"] = h.Status
}

func (h h1StudentSemesterBill) clone(db *gorm.DB) h1StudentSemesterBill {
	h.h1StudentSemesterBillDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1StudentSemesterBill) replaceDB(db *gorm.DB) h1StudentSemesterBill {
	h.h1StudentSemesterBillDo.ReplaceDB(db)
	return h
}

type h1StudentSemesterBillDo struct{ gen.DO }

type IH1StudentSemesterBillDo interface {
	gen.SubQuery
	Debug() IH1StudentSemesterBillDo
	WithContext(ctx context.Context) IH1StudentSemesterBillDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1StudentSemesterBillDo
	WriteDB() IH1StudentSemesterBillDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1StudentSemesterBillDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1StudentSemesterBillDo
	Not(conds ...gen.Condition) IH1StudentSemesterBillDo
	Or(conds ...gen.Condition) IH1StudentSemesterBillDo
	Select(conds ...field.Expr) IH1StudentSemesterBillDo
	Where(conds ...gen.Condition) IH1StudentSemesterBillDo
	Order(conds ...field.Expr) IH1StudentSemesterBillDo
	Distinct(cols ...field.Expr) IH1StudentSemesterBillDo
	Omit(cols ...field.Expr) IH1StudentSemesterBillDo
	Join(table schema.Tabler, on ...field.Expr) IH1StudentSemesterBillDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1StudentSemesterBillDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1StudentSemesterBillDo
	Group(cols ...field.Expr) IH1StudentSemesterBillDo
	Having(conds ...gen.Condition) IH1StudentSemesterBillDo
	Limit(limit int) IH1StudentSemesterBillDo
	Offset(offset int) IH1StudentSemesterBillDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1StudentSemesterBillDo
	Unscoped() IH1StudentSemesterBillDo
	Create(values ...*model.H1StudentSemesterBill) error
	CreateInBatches(values []*model.H1StudentSemesterBill, batchSize int) error
	Save(values ...*model.H1StudentSemesterBill) error
	First() (*model.H1StudentSemesterBill, error)
	Take() (*model.H1StudentSemesterBill, error)
	Last() (*model.H1StudentSemesterBill, error)
	Find() ([]*model.H1StudentSemesterBill, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1StudentSemesterBill, err error)
	FindInBatches(result *[]*model.H1StudentSemesterBill, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1StudentSemesterBill) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1StudentSemesterBillDo
	Assign(attrs ...field.AssignExpr) IH1StudentSemesterBillDo
	Joins(fields ...field.RelationField) IH1StudentSemesterBillDo
	Preload(fields ...field.RelationField) IH1StudentSemesterBillDo
	FirstOrInit() (*model.H1StudentSemesterBill, error)
	FirstOrCreate() (*model.H1StudentSemesterBill, error)
	FindByPage(offset int, limit int) (result []*model.H1StudentSemesterBill, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1StudentSemesterBillDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1StudentSemesterBillDo) Debug() IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Debug())
}

func (h h1StudentSemesterBillDo) WithContext(ctx context.Context) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1StudentSemesterBillDo) ReadDB() IH1StudentSemesterBillDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1StudentSemesterBillDo) WriteDB() IH1StudentSemesterBillDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1StudentSemesterBillDo) Session(config *gorm.Session) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1StudentSemesterBillDo) Clauses(conds ...clause.Expression) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1StudentSemesterBillDo) Returning(value interface{}, columns ...string) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1StudentSemesterBillDo) Not(conds ...gen.Condition) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1StudentSemesterBillDo) Or(conds ...gen.Condition) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1StudentSemesterBillDo) Select(conds ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1StudentSemesterBillDo) Where(conds ...gen.Condition) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1StudentSemesterBillDo) Order(conds ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1StudentSemesterBillDo) Distinct(cols ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1StudentSemesterBillDo) Omit(cols ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1StudentSemesterBillDo) Join(table schema.Tabler, on ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1StudentSemesterBillDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1StudentSemesterBillDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1StudentSemesterBillDo) Group(cols ...field.Expr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1StudentSemesterBillDo) Having(conds ...gen.Condition) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1StudentSemesterBillDo) Limit(limit int) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1StudentSemesterBillDo) Offset(offset int) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1StudentSemesterBillDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1StudentSemesterBillDo) Unscoped() IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1StudentSemesterBillDo) Create(values ...*model.H1StudentSemesterBill) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1StudentSemesterBillDo) CreateInBatches(values []*model.H1StudentSemesterBill, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1StudentSemesterBillDo) Save(values ...*model.H1StudentSemesterBill) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1StudentSemesterBillDo) First() (*model.H1StudentSemesterBill, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1StudentSemesterBill), nil
	}
}

func (h h1StudentSemesterBillDo) Take() (*model.H1StudentSemesterBill, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1StudentSemesterBill), nil
	}
}

func (h h1StudentSemesterBillDo) Last() (*model.H1StudentSemesterBill, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1StudentSemesterBill), nil
	}
}

func (h h1StudentSemesterBillDo) Find() ([]*model.H1StudentSemesterBill, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1StudentSemesterBill), err
}

func (h h1StudentSemesterBillDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1StudentSemesterBill, err error) {
	buf := make([]*model.H1StudentSemesterBill, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1StudentSemesterBillDo) FindInBatches(result *[]*model.H1StudentSemesterBill, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1StudentSemesterBillDo) Attrs(attrs ...field.AssignExpr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1StudentSemesterBillDo) Assign(attrs ...field.AssignExpr) IH1StudentSemesterBillDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1StudentSemesterBillDo) Joins(fields ...field.RelationField) IH1StudentSemesterBillDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1StudentSemesterBillDo) Preload(fields ...field.RelationField) IH1StudentSemesterBillDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1StudentSemesterBillDo) FirstOrInit() (*model.H1StudentSemesterBill, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1StudentSemesterBill), nil
	}
}

func (h h1StudentSemesterBillDo) FirstOrCreate() (*model.H1StudentSemesterBill, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1StudentSemesterBill), nil
	}
}

func (h h1StudentSemesterBillDo) FindByPage(offset int, limit int) (result []*model.H1StudentSemesterBill, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1StudentSemesterBillDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1StudentSemesterBillDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1StudentSemesterBillDo) Delete(models ...*model.H1StudentSemesterBill) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1StudentSemesterBillDo) withDO(do gen.Dao) *h1StudentSemesterBillDo {
	h.DO = *do.(*gen.DO)
	return h
}
