// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"demo/dal/model"
)

func newH1Student(db *gorm.DB, opts ...gen.DOOption) h1Student {
	_h1Student := h1Student{}

	_h1Student.h1StudentDo.UseDB(db, opts...)
	_h1Student.h1StudentDo.UseModel(&model.H1Student{})

	tableName := _h1Student.h1StudentDo.TableName()
	_h1Student.ALL = field.NewAsterisk(tableName)
	_h1Student.ID = field.NewInt64(tableName, "id")
	_h1Student.Name = field.NewString(tableName, "name")
	_h1Student.Contact = field.NewString(tableName, "contact")
	_h1Student.DiscountRate = field.NewFloat64(tableName, "discount_rate")

	_h1Student.fillFieldMap()

	return _h1Student
}

type h1Student struct {
	h1StudentDo h1StudentDo

	ALL          field.Asterisk
	ID           field.Int64
	Name         field.String
	Contact      field.String
	DiscountRate field.Float64

	fieldMap map[string]field.Expr
}

func (h h1Student) Table(newTableName string) *h1Student {
	h.h1StudentDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h h1Student) As(alias string) *h1Student {
	h.h1StudentDo.DO = *(h.h1StudentDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *h1Student) updateTableName(table string) *h1Student {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Name = field.NewString(table, "name")
	h.Contact = field.NewString(table, "contact")
	h.DiscountRate = field.NewFloat64(table, "discount_rate")

	h.fillFieldMap()

	return h
}

func (h *h1Student) WithContext(ctx context.Context) IH1StudentDo {
	return h.h1StudentDo.WithContext(ctx)
}

func (h h1Student) TableName() string { return h.h1StudentDo.TableName() }

func (h h1Student) Alias() string { return h.h1StudentDo.Alias() }

func (h h1Student) Columns(cols ...field.Expr) gen.Columns { return h.h1StudentDo.Columns(cols...) }

func (h *h1Student) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *h1Student) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 4)
	h.fieldMap["id"] = h.ID
	h.fieldMap["name"] = h.Name
	h.fieldMap["contact"] = h.Contact
	h.fieldMap["discount_rate"] = h.DiscountRate
}

func (h h1Student) clone(db *gorm.DB) h1Student {
	h.h1StudentDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h h1Student) replaceDB(db *gorm.DB) h1Student {
	h.h1StudentDo.ReplaceDB(db)
	return h
}

type h1StudentDo struct{ gen.DO }

type IH1StudentDo interface {
	gen.SubQuery
	Debug() IH1StudentDo
	WithContext(ctx context.Context) IH1StudentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IH1StudentDo
	WriteDB() IH1StudentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IH1StudentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IH1StudentDo
	Not(conds ...gen.Condition) IH1StudentDo
	Or(conds ...gen.Condition) IH1StudentDo
	Select(conds ...field.Expr) IH1StudentDo
	Where(conds ...gen.Condition) IH1StudentDo
	Order(conds ...field.Expr) IH1StudentDo
	Distinct(cols ...field.Expr) IH1StudentDo
	Omit(cols ...field.Expr) IH1StudentDo
	Join(table schema.Tabler, on ...field.Expr) IH1StudentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IH1StudentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IH1StudentDo
	Group(cols ...field.Expr) IH1StudentDo
	Having(conds ...gen.Condition) IH1StudentDo
	Limit(limit int) IH1StudentDo
	Offset(offset int) IH1StudentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IH1StudentDo
	Unscoped() IH1StudentDo
	Create(values ...*model.H1Student) error
	CreateInBatches(values []*model.H1Student, batchSize int) error
	Save(values ...*model.H1Student) error
	First() (*model.H1Student, error)
	Take() (*model.H1Student, error)
	Last() (*model.H1Student, error)
	Find() ([]*model.H1Student, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Student, err error)
	FindInBatches(result *[]*model.H1Student, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.H1Student) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IH1StudentDo
	Assign(attrs ...field.AssignExpr) IH1StudentDo
	Joins(fields ...field.RelationField) IH1StudentDo
	Preload(fields ...field.RelationField) IH1StudentDo
	FirstOrInit() (*model.H1Student, error)
	FirstOrCreate() (*model.H1Student, error)
	FindByPage(offset int, limit int) (result []*model.H1Student, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IH1StudentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h h1StudentDo) Debug() IH1StudentDo {
	return h.withDO(h.DO.Debug())
}

func (h h1StudentDo) WithContext(ctx context.Context) IH1StudentDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h h1StudentDo) ReadDB() IH1StudentDo {
	return h.Clauses(dbresolver.Read)
}

func (h h1StudentDo) WriteDB() IH1StudentDo {
	return h.Clauses(dbresolver.Write)
}

func (h h1StudentDo) Session(config *gorm.Session) IH1StudentDo {
	return h.withDO(h.DO.Session(config))
}

func (h h1StudentDo) Clauses(conds ...clause.Expression) IH1StudentDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h h1StudentDo) Returning(value interface{}, columns ...string) IH1StudentDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h h1StudentDo) Not(conds ...gen.Condition) IH1StudentDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h h1StudentDo) Or(conds ...gen.Condition) IH1StudentDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h h1StudentDo) Select(conds ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h h1StudentDo) Where(conds ...gen.Condition) IH1StudentDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h h1StudentDo) Order(conds ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h h1StudentDo) Distinct(cols ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h h1StudentDo) Omit(cols ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h h1StudentDo) Join(table schema.Tabler, on ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h h1StudentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h h1StudentDo) RightJoin(table schema.Tabler, on ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h h1StudentDo) Group(cols ...field.Expr) IH1StudentDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h h1StudentDo) Having(conds ...gen.Condition) IH1StudentDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h h1StudentDo) Limit(limit int) IH1StudentDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h h1StudentDo) Offset(offset int) IH1StudentDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h h1StudentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IH1StudentDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h h1StudentDo) Unscoped() IH1StudentDo {
	return h.withDO(h.DO.Unscoped())
}

func (h h1StudentDo) Create(values ...*model.H1Student) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h h1StudentDo) CreateInBatches(values []*model.H1Student, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h h1StudentDo) Save(values ...*model.H1Student) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h h1StudentDo) First() (*model.H1Student, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Student), nil
	}
}

func (h h1StudentDo) Take() (*model.H1Student, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Student), nil
	}
}

func (h h1StudentDo) Last() (*model.H1Student, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Student), nil
	}
}

func (h h1StudentDo) Find() ([]*model.H1Student, error) {
	result, err := h.DO.Find()
	return result.([]*model.H1Student), err
}

func (h h1StudentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.H1Student, err error) {
	buf := make([]*model.H1Student, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h h1StudentDo) FindInBatches(result *[]*model.H1Student, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h h1StudentDo) Attrs(attrs ...field.AssignExpr) IH1StudentDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h h1StudentDo) Assign(attrs ...field.AssignExpr) IH1StudentDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h h1StudentDo) Joins(fields ...field.RelationField) IH1StudentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h h1StudentDo) Preload(fields ...field.RelationField) IH1StudentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h h1StudentDo) FirstOrInit() (*model.H1Student, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Student), nil
	}
}

func (h h1StudentDo) FirstOrCreate() (*model.H1Student, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.H1Student), nil
	}
}

func (h h1StudentDo) FindByPage(offset int, limit int) (result []*model.H1Student, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h h1StudentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h h1StudentDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h h1StudentDo) Delete(models ...*model.H1Student) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *h1StudentDo) withDO(do gen.Dao) *h1StudentDo {
	h.DO = *do.(*gen.DO)
	return h
}
