// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdmin = "admins"

// Admin mapped from table <admins>
type Admin struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Password  string         `gorm:"column:password;not null" json:"password"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
