// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameH1Attendance = "h1_attendance"

// H1Attendance mapped from table <h1_attendance>
type H1Attendance struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ScheduleID       int64     `gorm:"column:schedule_id;not null" json:"schedule_id"`
	StudentID        int64     `gorm:"column:student_id;not null" json:"student_id"`
	CheckedAt        time.Time `gorm:"column:checked_at" json:"checked_at"`
	Status           string    `gorm:"column:status;not null" json:"status"`
	MakeupScheduleID *int64    `gorm:"column:makeup_schedule_id" json:"makeup_schedule_id"`
}

// TableName H1Attendance's table name
func (*H1Attendance) TableName() string {
	return TableNameH1Attendance
}
