// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameH1Course = "h1_course"

// H1Course mapped from table <h1_course>
type H1Course struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName H1Course's table name
func (*H1Course) TableName() string {
	return TableNameH1Course
}
