// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameH1ClassCourse = "h1_class_course"

// H1ClassCourse mapped from table <h1_class_course>
type H1ClassCourse struct {
	ID           int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClassID      int64   `gorm:"column:class_id;not null" json:"class_id"`
	CourseID     int64   `gorm:"column:course_id;not null" json:"course_id"`
	SemesterID   int64   `gorm:"column:semester_id;not null" json:"semester_id"`
	PricePerHour float64 `gorm:"column:price_per_hour;not null" json:"price_per_hour"`
}

// TableName H1ClassCourse's table name
func (*H1ClassCourse) TableName() string {
	return TableNameH1ClassCourse
}
