// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameH1Class = "h1_class"

// H1Class mapped from table <h1_class>
type H1Class struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string `gorm:"column:name;not null" json:"name"`
	SemesterID int64  `gorm:"column:semester_id;not null" json:"semester_id"`
}

// TableName H1Class's table name
func (*H1Class) TableName() string {
	return TableNameH1Class
}
