// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameH1Enrollment = "h1_enrollment"

// H1Enrollment mapped from table <h1_enrollment>
type H1Enrollment struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StudentID     int64     `gorm:"column:student_id;not null" json:"student_id"`
	ClassCourseID int64     `gorm:"column:class_course_id;not null" json:"class_course_id"`
	EnrolledAt    time.Time `gorm:"column:enrolled_at;default:CURRENT_TIMESTAMP" json:"enrolled_at"`
}

// TableName H1Enrollment's table name
func (*H1Enrollment) TableName() string {
	return TableNameH1Enrollment
}
