// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameH1Student = "h1_student"

// H1Student mapped from table <h1_student>
type H1Student struct {
	ID           int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string  `gorm:"column:name;not null" json:"name"`
	Contact      string  `gorm:"column:contact" json:"contact"`
	DiscountRate float64 `gorm:"column:discount_rate;default:1.00" json:"discount_rate"`
}

// TableName H1Student's table name
func (*H1Student) TableName() string {
	return TableNameH1Student
}
