// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameH1Schedule = "h1_schedule"

// H1Schedule mapped from table <h1_schedule>
type H1Schedule struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClassCourseID int64     `gorm:"column:class_course_id;not null" json:"class_course_id"`
	Date          time.Time `gorm:"column:date;not null" json:"date"`
	StartTime     time.Time `gorm:"column:start_time" json:"start_time"`
	EndTime       time.Time `gorm:"column:end_time" json:"end_time"`
}

// TableName H1Schedule's table name
func (*H1Schedule) TableName() string {
	return TableNameH1Schedule
}
