// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameH1StudentSemesterBill = "h1_student_semester_bill"

// H1StudentSemesterBill mapped from table <h1_student_semester_bill>
type H1StudentSemesterBill struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StudentID   int64     `gorm:"column:student_id;not null" json:"student_id"`
	SemesterID  int64     `gorm:"column:semester_id;not null" json:"semester_id"`
	TotalFee    float64   `gorm:"column:total_fee;not null" json:"total_fee"`
	FinalizedAt time.Time `gorm:"column:finalized_at;default:CURRENT_TIMESTAMP" json:"finalized_at"`
	Status      string    `gorm:"column:status;default:未结算" json:"status"`
}

// TableName H1StudentSemesterBill's table name
func (*H1StudentSemesterBill) TableName() string {
	return TableNameH1StudentSemesterBill
}
