// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInfo = "infos"

// Info mapped from table <infos>
type Info struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Sid       string `gorm:"column:sid;not null" json:"sid"`
	ClassID   int64  `gorm:"column:class_id" json:"class_id"`
	Name      string `gorm:"column:name" json:"name"`
	Gender    string `gorm:"column:gender" json:"gender"`
	Email     string `gorm:"column:email" json:"email"`
	Telephone string `gorm:"column:telephone" json:"telephone"`
}

// TableName Info's table name
func (*Info) TableName() string {
	return TableNameInfo
}
