// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMajor = "majors"

// Major mapped from table <majors>
type Major struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	SchoolID  int64          `gorm:"column:school_id;not null" json:"school_id"`
}

// TableName Major's table name
func (*Major) TableName() string {
	return TableNameMajor
}
